openapi: "3.0.1"
info:
  title: "ImportApi"
  version: "2023-06-15 20:21:05UTC"
servers:
- url: "https://vaa4ihg2mb.execute-api.eu-west-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
tags:
- name: "aws:cloudformation:stack-id"
  x-amazon-apigateway-tag-value: "arn:aws:cloudformation:eu-west-1:158561360962:stack/ImportServiceStack/1f76bca0-0bb7-11ee-973b-06539361bf43"
- name: "aws:cloudformation:stack-name"
  x-amazon-apigateway-tag-value: "ImportServiceStack"
- name: "aws:cloudformation:logical-id"
  x-amazon-apigateway-tag-value: "ImportApiA8B26420"
paths:
  /import:
    get:
      responses:
        default:
          description: "Default response for GET /import"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:158561360962:function:importProductsFile/invocations"
        connectionType: "INTERNET"
components:
  x-amazon-apigateway-integrations:
    unusedIntegration_ivo5lnc:
      payloadFormatVersion: "2.0"
      type: "aws_proxy"
      httpMethod: "POST"
      uri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:158561360962:function:importProductsFile/invocations"
      connectionType: "INTERNET"
x-amazon-apigateway-cors:
  allowMethods:
  - "*"
  allowHeaders:
  - "*"
  maxAge: -42
  allowCredentials: false
  allowOrigins:
  - "*"
x-amazon-apigateway-importexport-version: "1.0"
